services:
  postgres:
    image: "postgres:17.2"
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - ~/mailer-data:/var/lib/postgresql/data:rw
  server:
    restart: always
    build: .
    env_file: .env
    ports:
      - 88:80

