services:
  postgres:
    image: "postgres:17.2"
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  server:
    restart: always
    build: .
    env_file: .env
  bot:
    restart: always
    build: .
    command: "npm run bot"
    env_file: .env
